name: 'Test Action'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-should-complain-about-missing-api-key:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Upload reports using a glob pattern
        uses: ./
        id: test_step
        with:
          github-token: ${{ github.token }}
          logs: "true"
          files: '**/fixtures/**'
          service: junit-upload-github-action-tests
          env: ci
          tags: "foo:bar,alpha:bravo"
        continue-on-error: true
      - name: Check that previous step failed
        if: steps.test_step.outcome == 'success'
        run: |
          echo "The previous step did not fail as expected"
          exit 1
